Upgrade requirements in manifest.json
l-j/home-assistant-vacuum-styj02ym pull request #1
Opened 2021-03-16 22:59 UTC by mrwogu

There is a conflict with another HACS repository (https://github.com/syssi/xiaomi_airpurifier).
Using both platforms **xiaomi_miio_airpurifier** and **miio2** caused error with  xiaomi_miio_airpurifier which uses newer version of python-miio.

```
Platform error fan.xiaomi_miio_airpurifier - cannot import name 'FanMiot' from 'miio' (/usr/local/lib/python3.8/site-packages/miio/__init__.py)
```
(more here: https://github.com/syssi/xiaomi_airpurifier/issues/98)

This PR resolves this issue.

2021-03-18 16:40 UTC, l-j commented
Thanks for pointing it out, I do not have an air purifier. 

I will check whether everything works with your changes applied, give me a day or two for that.

2021-03-19 19:06 UTC, l-j requested changes
Works great!
Can you please fix those minor issues? I will merge the PR then.

2021-03-19 19:06 UTC, l-j commented on hacs.json
> +    "iot_class": "local_polling",
I think it should be `"Local Polling"` based on the documentation:
* https://www.home-assistant.io/blog/2016/02/12/classifying-the-internet-of-things
* https://hacs.xyz/docs/publish/start/

2021-03-19 19:06 UTC, l-j commented on hacs.json
> -    "filename": "miio2.zip"
Can you please do not remove those lines? I have already done a missing release.
```    
    "zip_release": true,
    "filename": "miio2.zip"	
```

2021-03-24 00:43 UTC, mrwogu commented
Done :)

2021-03-25 16:28 UTC, l-j approved these changes

2021-03-25 16:28 UTC, merged